### ISSUE TITLE
Option to bind the result list to another element

### ISSUE THREAD

**Issue by nicozimmermann94** [jstayton/jquery-marcopolo#32]
Hey there!
Because of variuos reasons, my input field is surrounded by a div with overflow: hidden. When the result get displayed, the ol gets trapped inside the div.
Is there a way to tell marcopolo to bind the result ol to another element? Maybe an option which expects a selector?

**Comment by jstayton** [comment]
Hi there,

Not out-of-the-box, no. But it may work to manually move it after setup. Something like:

```javascript
$('#userSearch').marcoPolo(options);

$('#userSearch').marcoPolo('list').appendTo('#anotherElement');
```

I haven't tried it, but it may just work.
