### ISSUE TITLE
Cant set initial value

### ISSUE THREAD

**Issue by caraionutz** [jstayton/jquery-marcopolo#33]
i cant set initial value even if i use <input type="text" name="userSearch" id="Cor" value="Win Butler">

this is my code
$('#Cor').marcoPolo({
	data: {
    limit: 10
   
  },
  
  url: 'ajax_actions.php?',
  formatItem: function (data, $item) {
    return data.info +' Cod Cor:'+ data.value;
  },
   minChars: 3,
  formatMinChars : function(minChars, $item) {
	return '<em>Introduceti minim <strong>' + minChars + '</strong> caractere.</em>'; 
  },
  onSelect: function (data, $item, initial) {
    this.val(data.info);
  }
});
Hope you can help me
thank you

**Comment by jstayton** [comment]
Hey @caraionutz,

Have you read [the wiki page on setting an initial value](https://github.com/jstayton/jquery-marcopolo/wiki/Setting-an-Initial-Value)?

Let me know if any further questions after looking that over. Thanks!

**Comment by caraionutz** [comment]
Hello, 

Yes ive tried all method with no results. Can you help me? Thank you

L.S

Pe 10 nov. 2015, la 20:39, Justin Stayton <notifications@github.com> a scris:

**Comment by jstayton** [comment]
Can you provide some more details — maybe even an example that shows the issue? The code in your original comment doesn't actually tell me how you're trying to set the initial value.

**Comment by caraionutz** [comment]
this is my htmlthat works and save the value into db, also read it. But it doenst show the result from db , if i check with firebug the results from db apear in value field, but is not vizibile on my site. i have also attached a print screen.

this is html code
<input type="text" id="Cor" class="form-control uppercase" name="Vars[ocupatia]" value="<?= (isset($membru['ocupatia'])) ? $membru['ocupatia'] : $update['ocupatia'];  ?>" />
this is my js code$('#Cor').marcoPolo({
    data: {
    limit: 10
   
  },
  
  url: 'ajax_actions.php?',
  formatItem: function (data, $item) {
    return data.info +' Cod Cor:'+ data.value;
  },
   minChars: 3,
  formatMinChars : function(minChars, $item) {
    return '<em>Introduceti minim <strong>' + minChars + '</strong> caractere.</em>'; 
  },
  onSelect: function (data, $item, initial) {
    this.val(data.info);
  }
});


thank you

**Comment by jstayton** [comment]
I think I know what's going on. Setting the initial value via the `value` attribute only works for simple string values. Looking at your JS code, you're expecting `ajax_actions.php` to return JSON (i.e., `data.info` and `data.value`). When Marco Polo is initialized, it takes the `value` attribute and passes it to your `onSelect` callback, so `data` is just a string — it's not an object. You should probably be seeing a JS error in Firebug.

What you need to do is set the initial value using the same JSON that's returned by `ajax_actions.php`. You can set this either through the `data-selected` attribute or `selected` option. You can see examples of how to do this in the wiki page I linked earlier.
