### ISSUE TITLE
Cache invalidate

### ISSUE THREAD

**Issue by horodchukanton** [jstayton/jquery-marcopolo#34]
Hello, can you implement an API function for cache invalidation?

**Comment by jstayton** [comment]
@horodchukanton I'm very sorry for never responding to you here. As my silence likely hinted, I stopped maintaining this project long ago. I'm now officially deprecating it to make that clear.

If you'd like to continue supporting a forked version, please reach out on Twitter ([@kidjustino](https://twitter.com/kidjustino)) to have it listed in the README.
