### ISSUE TITLE
Hide result numbers

### ISSUE THREAD

**Issue by Mohamm6d** [jstayton/jquery-marcopolo#35]
Hey,Thank you in advance for your good plugin
but I need to hide numbers in search result OL
How i can do it ?

**Comment by jstayton** [comment]
@Mohamm6d I'm very sorry for never responding to you here. As my silence likely hinted, I stopped maintaining this project long ago. I'm now officially deprecating it to make that clear.

If you'd like to continue supporting a forked version, please reach out on Twitter ([@kidjustino](https://twitter.com/kidjustino)) to have it listed in the README.
