### ISSUE TITLE
Make a GET request on mouse input.

### ISSUE THREAD

**Issue by in3rsha** [jstayton/jquery-marcopolo#36]
Hello there!

My javascript isn't great so I realize this may well be a trivial issue. But **is it possible for a search to be made when you paste in to the search box via the mouse?** At the moment it seems as thought a GET request is only fired on keyboard input.

I'm using the default code in the README example. How can I modify this so that a search is fired when text is pasted in to the element via the mouse (as well as with keyboard input)?

```
$('#userSearch').marcoPolo({
  url: '/users/search',
  formatItem: function (data, $item) {
    return data.first_name + ' ' + data.last_name;
  },
  onSelect: function (data, $item) {
    window.location = data.profile_url;
  }
});
```

**Comment by jstayton** [comment]
@in3rsha I'm very sorry for never responding to you here. As my silence likely hinted, I stopped maintaining this project long ago. I'm now officially deprecating it to make that clear.

If you'd like to continue supporting a forked version, please reach out on Twitter ([@kidjustino](https://twitter.com/kidjustino)) to have it listed in the README.
